import Head from 'next/head'
import styles from './layout.module.css'
import Image from 'next/image'
export default function Layout({ children }: any) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Learn Next</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>{children}</main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png" alt="Logo" width={100} height={100} />
                    </span>

                </a>

            </footer>
        </div>
    )
}